name: Docker Build and Push

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username marcelocollyer --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Extract tag name
        run: echo "TAG_NAME=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_ENV

      - name: Build and push Docker images
        run: |
          docker build -t marcelocollyer/microservice-a:${{ env.TAG_NAME }} ./microservices/microservice-a
          docker push marcelocollyer/microservice-a:${{ env.TAG_NAME }}
          docker build -t marcelocollyer/microservice-b:${{ env.TAG_NAME }} ./microservices/microservice-b
          docker push marcelocollyer/microservice-b:${{ env.TAG_NAME }}
          docker build -t marcelocollyer/microservice-c:${{ env.TAG_NAME }} ./microservices/microservice-c
          docker push marcelocollyer/microservice-c:${{ env.TAG_NAME }}

      - name: Checkout the infrastructure repo
        uses: actions/checkout@v2
        with:
          repository: 'marcelocollyer/infrastructure-k8s'
          token: ${{ secrets.GH_TOKEN }}
          path: 'infrastructure'

      - name: Update image tags in Rollout files
        run: |
          sed -i "s|marcelocollyer/microservice-a:v[0-9]*\.[0-9]*\.[0-9]*.*|marcelocollyer/microservice-a:${{ env.TAG_NAME }}|" ./infrastructure/apps/rollout.yaml
          sed -i "s|marcelocollyer/microservice-b:v[0-9]*\.[0-9]*\.[0-9]*.*|marcelocollyer/microservice-b:${{ env.TAG_NAME }}|" ./infrastructure/apps/rollout.yaml
          sed -i "s|marcelocollyer/microservice-c:v[0-9]*\.[0-9]*\.[0-9]*.*|marcelocollyer/microservice-c:${{ env.TAG_NAME }}|" ./infrastructure/apps/rollout.yaml
  
      - name: Commit and push changes
        run: |
          cd infrastructure
          git config --global user.email "marcelocollyer@gmail.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "[AUTOMATED] Update rollout files to use new image tag: ${{ env.TAG_NAME }}"
          git push origin HEAD:main
          git tag ${{ env.TAG_NAME }}
          git push origin ${{ env.TAG_NAME }}
