name: Docker Build and Push

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username marcelocollyer --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Extract tag name
        run: echo "TAG_NAME=$(echo ${GITHUB_REF#refs/tags/} | sed 's/refs\/heads\///')" >> $GITHUB_ENV

      - name: Build and push Docker image for microservice-a
        uses: docker/build-push-action@v2
        with:
          context: ./microservices/microservice-a
          file: ./microservices/microservice-a/Dockerfile
          push: true
          tags: marcelocollyer/microservice-a:${{ env.TAG_NAME }}

      - name: Build and push Docker image for microservice-b
        uses: docker/build-push-action@v2
        with:
          context: ./microservices/microservice-b
          file: ./microservices/microservice-b/Dockerfile
          push: true
          tags: marcelocollyer/microservice-b:${{ env.TAG_NAME }}

      - name: Build and push Docker image for microservice-c
        uses: docker/build-push-action@v2
        with:
          context: ./microservices/microservice-c
          file: ./microservices/microservice-c/Dockerfile
          push: true
          tags: marcelocollyer/microservice-c:${{ env.TAG_NAME }}

      - name: Checkout the infrastructure repo
        uses: actions/checkout@v2
        with:
          repository: 'marcelocollyer/infrastructure-k8s'
          token: ${{ secrets.GH_TOKEN }}
  
      - name: Update values.yaml with the new tag
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "Updating image tag to $TAG_NAME in values.yaml"
          sed -i "s/tag: \".*\"/tag: \"$TAG_NAME\"/" ./apps/values.yaml
  
      - name: Commit and push changes
        run: |
          git config --global user.email "marcelocollyer@gmail.com"
          git config --global user.name "GitHub Actions"
          git add ./apps/values.yaml
          git commit -m "Update Helm values to $TAG_NAME"
          git push origin HEAD:main
          git tag $TAG_NAME
          git push origin $TAG_NAME
  
      - name: Verify changes
        run: cat ./apps/values.yaml
